# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'easynvest-teste-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for easynvest-teste-ios
  pod 'IQKeyboardManager'
  pod 'SwiftLint'

end

target 'easynvest-teste-iosTests' do
  inherit! :search_paths
  pod 'Quick'
  pod 'Nimble'
end
